env:
  es6: true
  browser: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:react/recommended'
  - 'plugin:flowtype/recommended'
  - 'react-app'
plugins:
  - react
  - flowtype
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  react/self-closing-comp:
    - error
