version: '2'
services:
  api:
    build:
      context: server
      dockerfile: Dockerfile-dev
    volumes:
      - ./server:/app/server
    ports:
      - "8080:8080"
    command: "rerun --background -- bundle exec rackup --host :: -p 8080 -s thin"
