version: '2'
services:
  budget:
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - .:/app/server
      - ./database:/db
    environment:
      - JWT_SECRET=somesecret
    command: "bundle exec rackup --host :: -p 8080 -s thin"
